- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ username }}"

  pre_tasks:
    - name: update repositories
      become_user: root
      apt: update_cache=yes
      changed_when: false

  roles:
    - role: geerlingguy.docker
      become_user: root
      docker_install_compose: false
      docker_install_compose_plugin: true
      docker_compose_package: docker-compose-plugin
      docker_compose_package_state: present
      docker_users:
        - "{{ username }}"

  tasks:
    - name: dotfiles - clone repo
      ansible.builtin.git:
        repo: git@github.com:FilipHarald/dotfiles.git
        dest: "{{ home_dir }}/lol"

    - name: general - install packages
      become_user: root
      apt: name={{item}}
      with_items:
        - neovim
        - i3
        - stow
        - fzf
        - ripgrep
        - bat
        - curl

    # https://waylonwalker.com/install-rust/
    - name: rust - check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
      tags:
        - rust

    - name: rust - download installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: rust - install rust & cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: nodejs - install nvm
      become: no
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      tags:
        - nodejs

    - name: nodejs - install node
      become: no
      shell: >
        . {{ home_dir }}/.nvm/nvm.sh && nvm install {{ item }} && nvm use {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ home_dir }}"
        creates: "{{ home_dir }}/.nvm/versions/{{ item }}"
      loop:
        - 16
        - 18
      tags:
        - nodejs

    - name: nvim - install plugins
      command:
        cmd: nvim --headless +pluginstall +qall
        creates: "{{ home_dir }}/.local/share/nvim"
      tags:
        - nvim

    - name: ssh - generate key
      openssh_keypair:
        path: "{{ home_dir }}/.ssh/id_rsa"
      tags:
        - ssh
